### ISSUE TITLE
联系方式

### ISSUE THREAD

**Issue by mancong** [GdeiAssistant/GdeiAssistant#1]
前一度时间发现到您的项目，关注了一段时间，今天想再自己机器中部署一下，发现缺少部分的配置文件，所以向您求教。如果方便请留下您的联系方式方便向您请教。敬谢！

**Comment by Pigbibi** [comment]
你好，若你在使用过程中遇到问题，请联系邮箱：[gdeiassistant@gmail.com](mailto:gdeiassistant.cn)
